//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace msp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADOCIVIL
    {
        public int ESC_ISN { get; set; }
        public string ESC_DSC { get; set; }
    }
}
