//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace msp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BANCOMSPEntities : DbContext
    {
        public BANCOMSPEntities()
            : base("name=BANCOMSPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ESTADOCIVIL> ESTADOCIVIL { get; set; }
        public DbSet<PESSOA> PESSOA { get; set; }
        public DbSet<PROFISSAO> PROFISSAO { get; set; }
        public DbSet<RELIGIAO> RELIGIAO { get; set; }
        public DbSet<SEXO> SEXO { get; set; }
    }
}
